apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kombuchalyzer.fullname" . }}
  labels:
    {{- include "kombuchalyzer.labels" . | nindent 4 }}
  {{- if or .Values.configMapAnnotations .Values.annotations }}
  annotations:
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.configMapAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  {{- with .Values.serverConfig }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
